import type { Metadata } from "next";
import LanguageSwitcher from "../../../components/language-switcher";

export const metadata: Metadata = { title: "Choice AI | David Portfolio", description: "A local decision assistant MVP built through requirements, rule design, and Vibe Coding." };

export default function EnglishChoiceAIPage() {
  return (
    <main className="case-page english-page" lang="en">
      <nav className="case-nav" aria-label="Case navigation"><a href="/en">← Portfolio</a><strong>DAVID · CASE 01</strong><div className="case-nav-actions"><LanguageSwitcher current="en" zhHref="/work/choice-ai" enHref="/en/work/choice-ai" /><a href="mailto:18602172142@163.com">Contact ↗</a></div></nav>
      <section className="case-hero"><div className="case-hero-grid"><div><span className="case-label">OPERATIONS × PRODUCT × AI</span><h1>Choice AI<br />Personal Decision Assistant</h1><p className="case-lead">For everyday decisions overwhelmed by too many options and scattered information, I translated operational judgment into an executable requirement structure, recommendation logic, and interaction flow.</p><div className="case-status">Current result: a complete local MVP prepared for pilot testing. It has not yet undergone scaled real-user validation, and no business outcomes are fabricated.</div></div><div className="case-visual"><img src="/images/work/choice-ai-home.png" alt="Choice AI local application homepage" /><span className="case-visual-note">One clear answer first · Lower decision cost</span></div></div></section>
      <section className="case-body" aria-labelledby="choice-process-title"><div className="case-body-inner"><div className="case-body-heading"><h2 id="choice-process-title">From an operations problem<br />to a working product.</h2><p>The point was not simply to build a page. It was to define decision information, translate fuzzy preferences into computable conditions, and rank them into one explainable recommendation. Vibe Coding enabled delivery; requirement judgment and rule design made the product viable.</p></div><div className="case-step-grid">
        <article className="case-step"><span>01 / PROBLEM</span><h3>Frame the Decision</h3><p>Break hesitation into options, constraints, preference strength, and risk tolerance—without collecting irrelevant information.</p></article><article className="case-step"><span>02 / RULES</span><h3>Design Recommendation Logic</h3><p>Combine hard filters, preference weights, and explanations so each result can be understood and reviewed.</p></article><article className="case-step"><span>03 / FLOW</span><h3>Reduce Interaction Cost</h3><p>Use an Input–Confirm–Answer flow and place secondary information in the result explanation.</p></article><article className="case-step"><span>04 / BUILD</span><h3>Vibe Coding</h3><p>Deliver desktop and mobile interfaces, local data processing, and a stable end-to-end interaction loop.</p></article><article className="case-step"><span>05 / TEST</span><h3>Acceptance Testing</h3><p>Cover empty states, edge cases, conflicting preferences, and result consistency while refining prompts and rules.</p></article><article className="case-step"><span>06 / NEXT</span><h3>Next Validation</h3><p>Use task completion, recommendation adoption, and reuse rates to test whether Choice AI truly lowers decision cost.</p></article>
      </div></div></section>
      <footer className="case-outro"><h2>Next: AI Video Model Evaluation</h2><div className="case-outro-actions"><a className="button button-secondary" href="/en">Portfolio</a><a className="button button-primary" href="/en/work/ai-video-evaluation">Continue →</a></div></footer>
    </main>
  );
}
