import type { Metadata } from "next";
import LanguageSwitcher from "../components/language-switcher";

export const metadata: Metadata = {
  title: "David · Caobinshan | AI Content & Creator Growth",
  description: "Portfolio focused on content supply, creator ecosystem growth, and practical AI projects.",
};

export default function EnglishHome() {
  return (
    <main className="site-shell english-page" lang="en">
      <header className="site-header" aria-label="Primary navigation">
        <a className="brand" href="#top" aria-label="Back to top"><span className="brand-mark" aria-hidden="true">D</span><span className="brand-copy"><strong>DAVID · CAOBINSHAN</strong><small>AI GROWTH / SHANGHAI</small></span></a>
        <nav className="desktop-nav" aria-label="Homepage sections"><a href="#capabilities">Capabilities</a><a href="#work">Work</a><a href="#experience">Experience</a><a href="#aesthetic">Aesthetics</a></nav>
        <div className="header-actions"><LanguageSwitcher current="en" zhHref="/" enHref="/en" /><a className="header-contact" href="mailto:18602172142@163.com">Contact<span aria-hidden="true">↗</span></a></div>
      </header>

      <section className="hero" id="top" aria-labelledby="hero-title">
        <div className="hero-copy">
          <div className="eyebrow-row"><span className="eyebrow eyebrow-pink">AI CONTENT & CREATOR GROWTH</span></div>
          <h1 id="hero-title">Turning <span className="highlight">AI capabilities</span><br />into operational and growth outcomes.</h1>
          <p className="hero-intro">5+ years in content growth and creator ecosystem operations at ByteDance and Bilibili, with hands-on proof through AI products, model evaluation, and Vibe Coding.</p>
          <div className="hero-actions" aria-label="Hero actions"><a className="button button-primary" href="#work">View selected work <span aria-hidden="true">→</span></a><a className="button button-secondary" href="mailto:18602172142@163.com">Let’s talk</a></div>
          <div className="availability"><span className="availability-dot" aria-hidden="true" /><p>Open to opportunities in <strong>content, creator ecosystems, and growth at AI startups</strong></p></div>
        </div>
        <div className="hero-visual" aria-label="David portrait"><div className="sticker sticker-top">AI × GROWTH</div><div className="sticker sticker-side">CONTENT +</div><div className="portrait-frame"><div className="dot-grid" /><div className="shape shape-circle" /><div className="shape shape-square" /><div className="shape shape-pill" /><div className="portrait-photo"><img src="/images/david-avatar-headshot.jpg" alt="Illustrated portrait of David wearing glasses and headphones" width="1000" height="1000" fetchPriority="high" /></div><div className="frame-caption"><span>01</span><span>DAVID / 2026</span></div></div><div className="visual-note"><span aria-hidden="true">✦</span>Bringing model capabilities into real operations</div></div>
      </section>

      <div className="hero-footer" aria-hidden="true"><span>STRATEGY</span><i /><span>PRODUCT PRACTICE</span><i /><span>CREATOR ECOSYSTEM</span><strong>SCROLL ↓</strong></div>

      <section className="page-section capabilities-section" id="capabilities" aria-labelledby="capabilities-title">
        <div className="section-heading split-heading"><div><span className="section-kicker">WHAT I CAN DO / 02</span><h2 id="capabilities-title">Build repeatable growth systems<br />for content and creators.</h2></div><p>From content direction and creator identification to tiered incentives—supported by AI tools for faster judgment and delivery.</p></div>
        <div className="capability-grid">
          <article className="capability-card capability-yellow"><span className="card-index">01</span><div className="capability-icon" aria-hidden="true">◎</div><h3>Content Supply</h3><p>Identify content opportunities, design formats, and turn proven practices into sustainable supply systems.</p><ul><li>Content and scenario judgment</li><li>Format and supply design</li><li>Performance review</li></ul></article>
          <article className="capability-card capability-pink"><span className="card-index">02</span><div className="capability-icon" aria-hidden="true">↗</div><h3>Creator Growth</h3><p>Build the full creator lifecycle from identification and acquisition to segmentation, activation, and retention.</p><ul><li>Creator profiles and standards</li><li>Tiering and incentives</li><li>Private-community lifecycle</li></ul></article>
          <article className="capability-card capability-mint"><span className="card-index">03</span><div className="capability-icon" aria-hidden="true">✦</div><h3>AI Enablement</h3><p>Apply models and tools to content production, creator workflows, and productized operations.</p><ul><li>Model and scenario evaluation</li><li>AI content workflows</li><li>Vibe Coding practice</li></ul></article>
        </div>
      </section>

      <section className="page-section work-section" id="work" aria-labelledby="work-title">
        <div className="section-heading split-heading"><div><span className="section-kicker">SELECTED PRACTICE / 03</span><h2 id="work-title">Selected Work</h2></div><p>Real projects that demonstrate requirement framing, model judgment, and executable product and content delivery.</p></div>
        <div className="work-grid">
          <a className="work-card work-card-choice" href="/en/work/choice-ai" aria-label="View Choice AI case study"><div className="work-media"><img src="/images/work/choice-ai-home.png" alt="Choice AI local application homepage" loading="lazy" /><span className="work-badge">VIBE CODING</span></div><div className="work-copy"><span className="work-number">CASE 01</span><h3>Choice AI<br />Personal Decision Assistant</h3><p>A productized operations project spanning requirements, recommendation rules, interaction flow, and a local MVP.</p><div className="work-tags"><span>Requirements</span><span>Rule Design</span><span>Local MVP</span></div><strong>View case <span aria-hidden="true">↗</span></strong></div></a>
          <a className="work-card work-card-video" href="/en/work/ai-video-evaluation" aria-label="View AI video model evaluation case study"><div className="work-copy"><span className="work-number">CASE 02</span><h3>AI Video Models<br />Evaluation & Creation</h3><p>A unified evaluation across 6 models and 7 metrics, followed by a multi-shot AI film.</p><div className="work-tags"><span>Model Judgment</span><span>Content Creation</span><span>KOL Scenarios</span></div><strong>View case <span aria-hidden="true">↗</span></strong></div><div className="work-media"><img src="/images/work/dragon-conquest-poster.jpg" alt="Dragon Conquest AI film poster" loading="lazy" /><span className="work-badge">6 MODELS / 7 METRICS</span></div></a>
        </div>
      </section>

      <section className="proof-strip" aria-labelledby="proof-title"><div className="proof-inner"><div className="proof-intro"><span className="section-kicker">EVIDENCE / 04</span><h2 id="proof-title">Content and creator growth<br />must produce real outcomes.</h2></div><div className="proof-grid"><article><strong>20k+</strong><span>High-potential creators</span><p>Standards, selection, and scaled operations</p></article><article><strong>50B+</strong><span>Format-driven views</span><p>Accumulated content consumption across hit formats</p></article><article><strong>10k+</strong><span>Overseas KOLs</span><p>Acquisition, private-community activation, retention</p></article><article><strong>5+</strong><span>Years of experience</span><p>Content supply, creator ecosystems, and AI practice</p></article></div></div></section>

      <section className="page-section experience-section" id="experience" aria-labelledby="experience-title"><div className="section-heading split-heading"><div><span className="section-kicker">EXPERIENCE / 05</span><h2 id="experience-title">Building growth systems<br />around creators and content.</h2></div><p>Across different products and markets, the core problem stays the same: find the right creators and help strong content happen continuously.</p></div><div className="timeline">
        <article className="timeline-item"><div className="timeline-meta"><span>2025.11—2026.01</span><strong>BILIBILI</strong></div><div className="timeline-main"><h3>Bilibili · Star Plan Creator Strategy</h3><p>Defined high-potential creator standards across AIGC, food, and entertainment; drove scaled acquisition and quality control.</p></div><div className="timeline-result"><strong>3k+</strong><span>Emerging creators</span><em>+25% graduation rate to 10k followers</em></div></article>
        <article className="timeline-item"><div className="timeline-meta"><span>2025.02—2025.11</span><strong>DOUYIN</strong></div><div className="timeline-main"><h3>Douyin · Format Creator Growth</h3><p>Built creator standards, segmentation, acquisition, incentives, and distribution support for ongoing format supply.</p></div><div className="timeline-result"><strong>20k+</strong><span>High-potential creators</span><em>50B+ format-driven views</em></div></article>
        <article className="timeline-item"><div className="timeline-meta"><span>2023.07—2025.02</span><strong>KE SONG</strong></div><div className="timeline-main"><h3>Kesong · Community Creator Operations</h3><p>Helped launch a new community from zero, covering vertical creator acquisition, activation, private groups, and content supply.</p></div><div className="timeline-result"><strong>2k+</strong><span>Original creators</span><em>10k+ distributable posts</em></div></article>
        <article className="timeline-item"><div className="timeline-meta"><span>2022.02—2023.02</span><strong>BILIBILI SEA</strong></div><div className="timeline-main"><h3>Bilibili Overseas · KOL Ecosystem</h3><p>Built KOL acquisition, private-community onboarding, tiered incentives, activation, and retention across Southeast Asia.</p></div><div className="timeline-result"><strong>10k+</strong><span>Overseas KOLs</span><em>14% of platform video views</em></div></article>
      </div></section>

      <section className="page-section social-section" aria-labelledby="social-title"><div className="section-heading split-heading"><div><span className="section-kicker">AI CONTENT & SOCIAL / 06</span><h2 id="social-title">Keep publishing. Keep connecting.</h2></div><p>I document my AI learning and practice publicly, and welcome conversations with people in content, creator ecosystems, and AI startups.</p></div><div className="social-grid"><a className="social-card xhs-card" href="https://xhslink.cn/m/86L73Xp4D18" target="_blank" rel="noreferrer"><div className="social-sticker">Visit profile ↗</div><span className="social-platform">REDNOTE / XIAOHONGSHU</span><h3>David Thinks<br />(AI Edition)</h3><p>Notes on AI tools, product experiences, model observations, and content operations.</p><div className="topic-cloud"><span>AI Tools</span><span>Products</span><span>Content Ops</span><span>Vibe Coding</span></div></a><article className="social-card bonjour-card"><div className="bonjour-copy"><span className="social-platform">BONJOUR / COFFEE CHAT</span><h3>Meet people with AI startup<br />and industry experience</h3><p>Displayed as a personal social card only—no account link or QR code.</p></div><img src="/images/social/bonjour-card.jpg" alt="Privacy-cropped Bonjour Coffee Chat card" loading="lazy" /></article></div></section>

      <section className="page-section aesthetic-section" id="aesthetic" aria-labelledby="aesthetic-title"><div className="section-heading split-heading"><div><span className="section-kicker">ABOUT AESTHETICS / 07</span><h2 id="aesthetic-title">Aesthetics<br /><span>Photography</span></h2></div><p>Photography trains me to observe relationships, find focal points, and structure a frame—the same abilities that support content judgment and storytelling.</p></div><div className="photo-grid"><figure><img src="/images/photography/01-snow-forest.jpg" alt="Snow forest with golden trees" loading="lazy" /><figcaption><span>01 / NATURE</span>Snow Forest</figcaption></figure><figure><img src="/images/photography/03-river-bridge.jpg" alt="Bridge under purple sunset" loading="lazy" /><figcaption><span>03 / CITY</span>Bridge at Sunset</figcaption></figure><figure><img src="/images/photography/04-shanghai-skyline.jpg" alt="Shanghai skyline at sunset" loading="lazy" /><figcaption><span>04 / CITY</span>Shanghai Skyline</figcaption></figure><figure><img src="/images/photography/05-city-contrast.jpg" alt="Traditional architecture and glass facade" loading="lazy" /><figcaption><span>05 / ARCHITECTURE</span>Tradition Meets Modernity</figcaption></figure><figure><img src="/images/photography/06-balloons.jpg" alt="Red and white balloons under blue sky" loading="lazy" /><figcaption><span>06 / DAILY LIFE</span>Balloons & Blue Sky</figcaption></figure><figure><img src="/images/photography/08-city-street.jpg" alt="Black and white city street" loading="lazy" /><figcaption><span>08 / STREET</span>Urban Order</figcaption></figure></div></section>

      <footer className="contact-footer" id="contact"><div className="footer-inner"><div><span className="section-kicker">LET’S TALK / 08</span><h2>If you work on AI, content,<br />or creator ecosystems, let’s talk.</h2></div><div className="contact-links"><a href="tel:18602172142"><span>PHONE</span><strong>186 0217 2142</strong><em>↗</em></a><a href="mailto:18602172142@163.com"><span>EMAIL</span><strong>18602172142@163.com</strong><em>↗</em></a><a href="https://xhslink.cn/m/86L73Xp4D18" target="_blank" rel="noreferrer"><span>REDNOTE</span><strong>David Thinks (AI Edition)</strong><em>↗</em></a></div></div><div className="footer-bottom footer-continuation"><span>To be continued...</span></div></footer>
    </main>
  );
}
